version: '3.8'

services:
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: martingaido00@gmail.com  # Cambia esto por tu correo electrónico
      PGADMIN_DEFAULT_PASSWORD: 1234           # Cambia esto por una contraseña segura
    ports:
      - "5050:80"  # Mapea el puerto 5050 de tu host al puerto 80 del contenedor
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    restart: unless-stopped

volumes:
  pgadmin_data:
